services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${PORT:-5000}:5000'
    environment:
      DEV_MONGO_URI: mongodb://mongo:27017/mydatabase
    depends_on:
      - mongo
    volumes:
      - .:/app
    env_file: .env
    restart: on-failure

  mongo:
    image: mongo:6
    ports:
      - '${MONGO_PORT:-27017}:27017'
    volumes:
      - mongo-data:/data/db
    restart: on-failure
    healthcheck:
      test:
        mongosh --eval 'db.runCommand("ping").ok' localhost:27017/test --quiet
      interval: 2s
      timeout: 3s
      retries: 5

  mailpit: # For email sending tests
    image: axllent/mailpit
    restart: always
    volumes:
      - ./.github:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_REQUIRE_STARTTLS: 0
      MP_SMTP_TLS_CERT: /data/cert.pem
      MP_SMTP_TLS_KEY: /data/key.pem
      MP_SMTP_AUTH: 'user1:password1 user2:password'

volumes:
  mongo-data:
  data:
